[project]
name = "try-discordpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.6.4",
    "discord-py>=2.4.0",
    "python-dotenv>=1.0.1",
]
